### ISSUE TITLE
希望合作

### ISSUE THREAD

**Issue by sunshineclt** [YunYinORG/find#1]
您好，我是NKU Helper的开发者，不知道您知不知道？我是个独立开发者，最近正希望做校园卡失物招领的平台，看到你们也是独立于学校非盈利的团队，不知道你们有没有兴趣合作？我可以在NKU Helper中嵌入校园卡失物招领的服务。

**Comment by NewFuture** [comment]
可以的，可以邮件联系确定一下接入接口，方便改版时同步~

-------- 原始邮件 --------
发件人：PikkaCho notifications@github.com
时间：周日 3月13日 23:19
收件人：YunYinORG/find find@noreply.github.com
主题：[find] 希望合作 (#1)

**Comment by NewFuture** [comment]
@sunshineclt  you can send an email  to contact#yunyin.org
